name: Daily_Post

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
jobs:
  Send_Note:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Python Install
        run: |
          python -m pip install --upgrade pip
          pip install Misskey.py
          pip install tweepy
          pip install Mastodon.py
          pip install atproto

      - name: Create Note Content
        env:
          MISSKEY_SERVER_ADDRESS: ${{ secrets.MISSKEY_SERVER_ADDRESS }}
          MISSKEY_TOKEN: ${{ secrets.MISSKEY_TOKEN }}
          MASTDON_BASE_URL: ${{ secrets.MASTDON_BASE_URL }}
          MASTDON_CLIENT_ID: ${{ secrets.MASTDON_CLIENT_ID }}
          MASTDON_SECRET: ${{ secrets.MASTDON_SECRET }}
          MASTDON_TOKEN: ${{ secrets.MASTDON_TOKEN }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          BLUESKY_MAIL_ADDRESS: ${{ secrets.BLUESKY_MAIL_ADDRESS }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}

        run: |
          python daily-picup.py
